global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'cryptkeeper'
    static_configs:
      - targets: ['cryptkeeper-app:8000', 'host.docker.internal:8000', 'localhost:8000']
